-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 11:53:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema City & Country
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `City & Country` ;

-- -----------------------------------------------------
-- Schema City & Country
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `City & Country` DEFAULT CHARACTER SET utf8 ;
USE `City & Country` ;

-- -----------------------------------------------------
-- Table `City & Country`.`Страна`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `City & Country`.`Страна` ;

CREATE TABLE IF NOT EXISTS `City & Country`.`Страна` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `City & Country`.`Область`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `City & Country`.`Область` ;

CREATE TABLE IF NOT EXISTS `City & Country`.`Область` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `City & Country`.`Район`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `City & Country`.`Район` ;

CREATE TABLE IF NOT EXISTS `City & Country`.`Район` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `district` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `City & Country`.`уровень города`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `City & Country`.`уровень города` ;

CREATE TABLE IF NOT EXISTS `City & Country`.`уровень города` (
  `ID` INT NOT NULL,
  `type_city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `City & Country`.`Город`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `City & Country`.`Город` ;

CREATE TABLE IF NOT EXISTS `City & Country`.`Город` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `id_country` INT NOT NULL,
  `id_region` INT NOT NULL,
  `id_district` INT NULL,
  `id_city` INT NOT NULL,
  `name_city` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID region _idx` (`id_region` ASC),
  INDEX `ID district_idx` (`id_district` ASC),
  INDEX `ID country_idx` (`id_country` ASC),
  INDEX `ID city_idx` (`id_city` ASC),
  CONSTRAINT `ID region `
    FOREIGN KEY (`id_region`)
    REFERENCES `City & Country`.`Область` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID district`
    FOREIGN KEY (`id_district`)
    REFERENCES `City & Country`.`Район` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID country`
    FOREIGN KEY (`id_country`)
    REFERENCES `City & Country`.`Страна` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID city`
    FOREIGN KEY (`id_city`)
    REFERENCES `City & Country`.`уровень города` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
