-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 20:25:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Страны и города мира
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Страны и города мира` ;

-- -----------------------------------------------------
-- Schema Страны и города мира
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Страны и города мира` DEFAULT CHARACTER SET utf8 ;
USE `Страны и города мира` ;

-- -----------------------------------------------------
-- Table `Страны и города мира`.`Страны`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Страны и города мира`.`Страны` ;

CREATE TABLE IF NOT EXISTS `Страны и города мира`.`Страны` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `страна` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `страна_UNIQUE` (`страна` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Страны и города мира`.`Область`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Страны и города мира`.`Область` ;

CREATE TABLE IF NOT EXISTS `Страны и города мира`.`Область` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id страны` INT UNSIGNED NOT NULL,
  `область` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `область_UNIQUE` (`область` ASC),
  INDEX `id страны_idx` (`id страны` ASC),
  CONSTRAINT `id страны`
    FOREIGN KEY (`id страны`)
    REFERENCES `Страны и города мира`.`Страны` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Страны и города мира`.`Районы`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Страны и города мира`.`Районы` ;

CREATE TABLE IF NOT EXISTS `Страны и города мира`.`Районы` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id страны` INT UNSIGNED NOT NULL,
  `id области` INT UNSIGNED NOT NULL,
  `район` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `район_UNIQUE` (`район` ASC),
  INDEX `id области_idx` (`id области` ASC),
  INDEX `id страны_idx` (`id страны` ASC),
  CONSTRAINT `id области`
    FOREIGN KEY (`id области`)
    REFERENCES `Страны и города мира`.`Область` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id страны`
    FOREIGN KEY (`id страны`)
    REFERENCES `Страны и города мира`.`Страны` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Страны и города мира`.`Города`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Страны и города мира`.`Города` ;

CREATE TABLE IF NOT EXISTS `Страны и города мира`.`Города` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id страны` INT UNSIGNED NOT NULL,
  `id области` INT UNSIGNED NOT NULL,
  `id района` INT UNSIGNED NOT NULL,
  `город` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `город_UNIQUE` (`город` ASC),
  INDEX `id района_idx` (`id района` ASC),
  INDEX `id области_idx` (`id области` ASC),
  INDEX `id страны_idx` (`id страны` ASC),
  CONSTRAINT `id района`
    FOREIGN KEY (`id района`)
    REFERENCES `Страны и города мира`.`Районы` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id области`
    FOREIGN KEY (`id области`)
    REFERENCES `Страны и города мира`.`Область` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id страны`
    FOREIGN KEY (`id страны`)
    REFERENCES `Страны и города мира`.`Страны` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
