-- MySQL Script generated by MySQL Workbench
-- Sat Aug 26 12:47:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop1` ;

-- -----------------------------------------------------
-- Schema shop1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop1` ;
-- -----------------------------------------------------
-- Schema World
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `World` ;

-- -----------------------------------------------------
-- Schema World
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `World` ;
USE `shop1` ;

-- -----------------------------------------------------
-- Table `shop1`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop1`.`Category` ;

CREATE TABLE IF NOT EXISTS `shop1`.`Category` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'Name of category',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop1`.`Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop1`.`Goods` ;

CREATE TABLE IF NOT EXISTS `shop1`.`Goods` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL COMMENT 'Name of goods',
  `Description` VARCHAR(255) NOT NULL COMMENT 'Product description',
  `Price` FLOAT NOT NULL COMMENT 'Price of goods',
  `count` INT ZEROFILL NOT NULL COMMENT 'Available in stock',
  `categoryID` INT NULL COMMENT 'Relationship to the \"category\" table',
  PRIMARY KEY (`ID`),
  INDEX `FK_category_idx` (`categoryID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop1`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop1`.`Order` ;

CREATE TABLE IF NOT EXISTS `shop1`.`Order` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL COMMENT 'order date ',
  `Adress` VARCHAR(255) NOT NULL COMMENT 'Delivery address',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop1`.`Order_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop1`.`Order_list` ;

CREATE TABLE IF NOT EXISTS `shop1`.`Order_list` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `GoodsID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_order_idx` (`OrderID` ASC),
  INDEX `fk_goods_idx` (`GoodsID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop1`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop1`.`table1` ;

CREATE TABLE IF NOT EXISTS `shop1`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop1`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop1`.`category` ;

CREATE TABLE IF NOT EXISTS `shop1`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));

USE `World` ;

-- -----------------------------------------------------
-- Table `World`.`Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `World`.`Region` ;

CREATE TABLE IF NOT EXISTS `World`.`Region` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CountryID` INT NOT NULL COMMENT '\nA foreign key identifying the country from the \"country\" table',
  `Name` VARCHAR(100) NOT NULL,
  `TextCode` VARCHAR(20) NOT NULL,
  `NumCode` INT NOT NULL,
  `AdmCenter` INT NOT NULL COMMENT '\nAdministrative center (A foreign key identifying the city from the \"city\" table)',
  `Population` INT NOT NULL,
  `DateUpdate` DATETIME NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  UNIQUE INDEX `TextCode_UNIQUE` (`TextCode` ASC),
  UNIQUE INDEX `NumCode_UNIQUE` (`NumCode` ASC),
  INDEX `fk_country_idx` (`CountryID` ASC),
  INDEX `fk_adm_center_idx` (`AdmCenter` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `World`.`Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `World`.`Area` ;

CREATE TABLE IF NOT EXISTS `World`.`Area` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CoutryID` INT NOT NULL COMMENT '\nA foreign key identifying the country from the \"country\" table',
  `RegionID` INT NOT NULL COMMENT '\nA foreign key identifying the region from the \"region\" table',
  `Name` VARCHAR(100) NOT NULL,
  `AdmCenter` INT NOT NULL COMMENT 'Administration center (A foreign key identifying the city  from the \"city\" table)',
  `Population` INT NOT NULL,
  `DateUpdate` DATETIME NULL DEFAULT NULL,
  `IsDleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  INDEX `fk_country_idx` (`CoutryID` ASC),
  INDEX `fa_region_idx` (`RegionID` ASC),
  INDEX `fk_adm_center_idx` (`AdmCenter` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `World`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `World`.`City` ;

CREATE TABLE IF NOT EXISTS `World`.`City` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CoutryID` INT NOT NULL COMMENT 'A foreign key identifying the country from the \"country\" table',
  `RegionID` INT NOT NULL COMMENT 'A foreign key identifying the region from the \"region\" table',
  `AreaID` INT NOT NULL COMMENT 'A foreign key identifying the area from the \"area\" table',
  ` Name` VARCHAR(50) NOT NULL,
  `Population` INT NOT NULL,
  `DateUpdate` DATETIME NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX ` Name_UNIQUE` (` Name` ASC),
  INDEX `fk_country_idx` (`CoutryID` ASC),
  INDEX `fk_region_idx` (`RegionID` ASC),
  INDEX `fk_area_idx` (`AreaID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `World`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `World`.`Country` ;

CREATE TABLE IF NOT EXISTS `World`.`Country` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL COMMENT '\nInternational name',
  `NumCode` TINYINT NOT NULL COMMENT 'ISO 3166-1 code (num)',
  `TextCode` VARCHAR(3) NOT NULL,
  `Founded` YEAR NOT NULL COMMENT '\nYear of foundation of the country',
  `CapitalCity` INT NOT NULL COMMENT 'The foreign key identifying the capital from the \"city\" table',
  `Langudge` VARCHAR(50) NOT NULL,
  `Population` INT NULL,
  `DateUpdate` DATETIME NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  UNIQUE INDEX `NumCode_UNIQUE` (`NumCode` ASC),
  UNIQUE INDEX `TextCode_UNIQUE` (`TextCode` ASC),
  INDEX `fk_capital_idx` (`CapitalCity` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
