-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 14:46:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `world` DEFAULT CHARACTER SET utf8 ;
USE `world` ;

-- -----------------------------------------------------
-- Table `mydb`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`countries` (
  `idcountry` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcountry`),
  UNIQUE INDEX `idcountries_UNIQUE` (`idcountry` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locality_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`locality_types` (
  `idlocality_type` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `locality_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlocality_type`),
  UNIQUE INDEX `idlocality_types_id_UNIQUE` (`idlocality_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`areas` (
  `idarea` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `area_name` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `idarea_UNIQUE` (`idarea` ASC),
  PRIMARY KEY (`idarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`regions` (
  `idregion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `region_name` VARCHAR(45) NOT NULL,
  `countries_idcountries` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idregion`),
  UNIQUE INDEX `idregion_UNIQUE` (`idregion` ASC),
  INDEX `fk_regions_countries1_idx` (`countries_idcountries` ASC),
  CONSTRAINT `fk_regions_countries1`
    FOREIGN KEY (`countries_idcountries`)
    REFERENCES `mydb`.`countries` (`idcountry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area_region_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`area_region_set` (
  `idarea_region_choice` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `areas_idarea` INT UNSIGNED NULL,
  `regions_idregion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idarea_region_choice`),
  UNIQUE INDEX `idarea_region_choice_UNIQUE` (`idarea_region_choice` ASC),
  INDEX `fk_area_region_set_areas1_idx` (`areas_idarea` ASC),
  INDEX `fk_area_region_set_regions1_idx` (`regions_idregion` ASC),
  CONSTRAINT `fk_area_region_set_areas1`
    FOREIGN KEY (`areas_idarea`)
    REFERENCES `mydb`.`areas` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_area_region_set_regions1`
    FOREIGN KEY (`regions_idregion`)
    REFERENCES `mydb`.`regions` (`idregion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`localities` (
  `idlocality` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `locality_name` VARCHAR(45) NOT NULL,
  `locality_type_id` INT UNSIGNED NOT NULL,
  `area_region_set_id` INT UNSIGNED NOT NULL,
  INDEX `fk_localities_locality_types_idx` (`locality_type_id` ASC),
  PRIMARY KEY (`idlocality`),
  UNIQUE INDEX `idlocality_UNIQUE` (`idlocality` ASC),
  INDEX `fk_localities_area_region_set1_idx` (`area_region_set_id` ASC),
  CONSTRAINT `fk_localities_locality_types`
    FOREIGN KEY (`locality_type_id`)
    REFERENCES `mydb`.`locality_types` (`idlocality_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_localities_area_region_set1`
    FOREIGN KEY (`area_region_set_id`)
    REFERENCES `mydb`.`area_region_set` (`idarea_region_choice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
