-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 21:40:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(100) NOT NULL COMMENT 'short country\'s name, Russia, for exp.',
  `full_country_name` VARCHAR(255) NOT NULL COMMENT 'full country\'s name , Russian Federation',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `country_name_UNIQUE` (`country_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`region` ;

CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region_name` VARCHAR(100) NOT NULL,
  `full_region_name` VARCHAR(255) NOT NULL,
  `id_country` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `region_name_UNIQUE` (`region_name` ASC),
  INDEX `fk_country_idx` (`id_country` ASC),
  CONSTRAINT `fk_country`
    FOREIGN KEY (`id_country`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`district`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`district` ;

CREATE TABLE IF NOT EXISTS `mydb`.`district` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `district_name` VARCHAR(255) NOT NULL,
  `id_region` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `district_name_UNIQUE` (`district_name` ASC),
  INDEX `fk_region_idx` (`id_region` ASC),
  CONSTRAINT `fk_region`
    FOREIGN KEY (`id_region`)
    REFERENCES `mydb`.`region` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`locality` ;

CREATE TABLE IF NOT EXISTS `mydb`.`locality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `id_district` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_district_idx` (`id_district` ASC),
  CONSTRAINT `fk_district`
    FOREIGN KEY (`id_district`)
    REFERENCES `mydb`.`district` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
